# Database setting
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/security_rest_jwt_db
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    
# Server setting
server:
  port: 8085

# Security setting   
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 3600000